### ISSUE TITLE
App crashing on Android -  couldn't find "libpjsua2.so"

### ISSUE THREAD

**Issue by marcelgoya** [symeonmattes/pjsip#4]
Hi there,

I've tried to use your plugin on Android and followed the steps from your description. When I run the App it does not seem to find the "libpjsua2.so" file for whatever reason, even though the file is inside the androidl/libs/armebi folder. Do you have any ideas how to fix the problem? 

Thanks,
Marcel

**Comment by symeonmattes** [comment]
what error does it give you?

2018-03-21 12:31 GMT+02:00 Marcel Goya <notifications@github.com>:

**Comment by marcelgoya** [comment]
The error is:

... couldn't find "libpjsua2.so"

**Comment by marcelgoya** [comment]
sorry, that's all there is plus it shows me all the directories its looking for

**Comment by symeonmattes** [comment]
I suppose you have tried to uninstall and reinstall the plugin.

Are you installing it on an ionic project?

**Comment by marcelgoya** [comment]
Yes, already did that but to no avail. Yup, it's an Ionic project.

**Comment by symeonmattes** [comment]
ok...did you manage to find a solution?

**Comment by marcelgoya** [comment]
Unfortunately not, so I had to use the cordova-sip plugin instead.
